version: "3.8"

services:
  web:
    image: python-app
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: bitnami/mysql:8.0.33-debian-11-r0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=myapp_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
