---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |-
    CREATE DATABASE IF NOT EXISTS myapp_db;
    USE myapp_db;
    CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
    GRANT ALL PRIVILEGES ON mysql_db.* TO '${MYSQL_USER}'@'%';
    FLUSH PRIVILEGES;

    CREATE TABLE IF NOT EXISTS items (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL
    );

    INSERT INTO items (name) VALUES ('Python');
    INSERT INTO items (name) VALUES ('GoLang');
    INSERT INTO items (name) VALUES ('PHP');
