name: Deploy to EKS

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.7
          backend-config: |
            {
              "bucket": "tfstate-comforte-prod",
              "key": "terraform-state/terraform.tfstate",
              "region": "eu-central-1"
            }

      - name: Set Terraform variables and Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var "aws_access_key=${AWS_ACCESS_KEY_ID}" -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}"

      - name: Push Terraform state to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          S3_BUCKET_NAME: tfstate-comforte-prod
          S3_DIR: terraform-state
        run: |
          cd terraform
          terraform init
          terraform state pull > terraform.tfstate
          aws s3 cp terraform.tfstate s3://${S3_BUCKET_NAME}/${S3_FOLDER_NAME}/terraform.tfstate --region ${AWS_DEFAULT_REGION}
