# name: Deploy to EKS

# on:
#   workflow_run:
#     workflows: ["Build"]
#     types:
#       - completed

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest

#     needs: build

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: eu-central-1

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.0.7

#       - name: Initialize Terraform working directory
#         working-directory: ./terraform
#         run: terraform init

#       - name: Apply Terraform configuration
#         working-directory: ./terraform
#         run: terraform apply -auto-approve

# - name: Push Terraform state file to S3 bucket
#   uses: aws-actions/amazon-s3-cp@v2
#   with:
#     source: ./terraform/terraform.tfstate
#     destination: s3://tfstate-comforte-prod/comforte-prod-terraform-state.tfstate
